version: '3.1'

services:
  app:
    image: 'construction-brazil-client'
    build: '.'
    ports:
      - 4200:80
    environment:
      - EEP_SERVER_URI=http://localhost:121
      - IS_POSTLOGOUT_REDIRECT_URI=http://localhost:121
      - IS_ENABLE_DEBUG_LOGGING=false

